# -*- coding: utf-8 -*-
"""Soal1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYmeYX746oWQ5kVo-FJq0MXZ1EvNZEhF
"""

def deteksi_hama(gejala):
    if "daun menguning" in gejala and "tanaman layu" in gejala:
        return "Kutu Daun"  # Aturan 1
    elif "daun menguning" in gejala and "bercak hitam" in gejala:
        return "Tungau"     # Aturan 4
    elif "bercak hitam" in gejala:
        return "Jamur"      # Aturan 2
    elif "daun berlubang" in gejala:
        return "Ulat Grayak"  # Aturan 3

    else:
        return "Hama tidak teridentifikasi"

# Contoh input gejala
gejala_input = ["bercak hitam"]  # ← Bisa ganti ini sesuai gejala yang ingin diuji

# Cetak hasil deteksi hama
hasil = deteksi_hama(gejala_input)
print("Jenis hama:", hasil)

"""```markdown
Penjelasan Program Deteksi Hama

Kode berikut adalah program sederhana untuk mendeteksi jenis hama tanaman berdasarkan gejala yang dialami tanaman. Program ini menggunakan aturan logika sederhana untuk mengambil keputusan.

Penjelasan Fungsi

def deteksi_hama(gejala):
    if "daun menguning" in gejala and "tanaman layu" in gejala:
        return "Kutu Daun"  # Aturan 1
    elif "daun menguning" in gejala and "bercak hitam" in gejala:
        return "Tungau"     # Aturan 4
    elif "bercak hitam" in gejala:
        return "Jamur"      # Aturan 2
    elif "daun berlubang" in gejala:
        return "Ulat Grayak"  # Aturan 3
    else:
        return "Hama tidak teridentifikasi"
```

- Fungsi `deteksi_hama` menerima **input** berupa `list` gejala tanaman.
- Program mengecek kondisi gejala:
  - Jika ada **daun menguning** dan **tanaman layu**, maka hasilnya **Kutu Daun** (Aturan 1).
  - Jika ada **daun menguning** dan **bercak hitam**, maka hasilnya **Tungau** (Aturan 4).
  - Jika hanya ada **bercak hitam**, maka hasilnya **Jamur** (Aturan 2).
  - Jika ada **daun berlubang**, maka hasilnya **Ulat Grayak** (Aturan 3).
- Jika gejala yang diberikan tidak cocok dengan aturan manapun, maka hasilnya adalah **Hama tidak teridentifikasi**.

## Contoh Penggunaan Program

```python
# Contoh input gejala
gejala_input = ["bercak hitam"]

# Menjalankan fungsi deteksi hama
hasil = deteksi_hama(gejala_input)

# Menampilkan hasil
print("Jenis hama:", hasil)
```

**Output yang dihasilkan:**
```
Jenis hama: Jamur
```

Program berhasil mendeteksi bahwa tanaman dengan gejala **bercak hitam** terkena serangan **jamur**.

## Kesimpulan

Program ini bekerja dengan mencocokkan daftar gejala yang diberikan terhadap aturan-aturan logika yang sudah ditentukan sebelumnya.  
Jika cocok, maka program akan memberikan jenis hama yang sesuai. Jika tidak, akan memberikan output "Hama tidak teridentifikasi".
"""